name: "Build"

on: 
  push:
    branches: '**'

jobs:
  build-job:
    runs-on: ${{ matrix.os }}
    name: "Build and test ${{ matrix.os }}"
    strategy:
      matrix:
        os: [windows-latest]
      
    steps:
    - name: "Setup node"
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: "Checkout source code"
      uses: "actions/checkout@v2"
    - name: "Install modules"
      run: "npm run install:ci"
    - name: "Build (npm)"
      run: "npm run build:web"
    - name: "Test"
      run: "npm test"
